// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ScriptoriumDbContext))]
    partial class ScriptoriumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Contexts.Annotation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contentUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'notImplemented.md'");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<int>("encyclopediaId")
                        .HasColumnType("int(11)");

                    b.Property<int>("endPage")
                        .HasColumnType("int(11)");

                    b.Property<int>("startPage")
                        .HasColumnType("int(11)");

                    b.Property<string>("tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("''");

                    b.Property<int>("themeId")
                        .HasColumnType("int(11)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "encyclopediaId" }, "Annotation_Encyclopedia_id_fk");

                    b.HasIndex(new[] { "themeId" }, "Annotation_Theme_Id_fk");

                    b.ToTable("Annotation", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Contexts.Encyclopedium", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("scribeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "scribeId" }, "Encyclopedia_Scribe_id_fk");

                    b.ToTable("Encyclopedia");
                });

            modelBuilder.Entity("Infrastructure.Contexts.Scribe", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "username" }, "Scribe_username_uk")
                        .IsUnique();

                    b.ToTable("Scribe", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Contexts.Theme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("folder")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "name" }, "Theme_name_uk")
                        .IsUnique();

                    b.ToTable("Theme", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Contexts.Annotation", b =>
                {
                    b.HasOne("Infrastructure.Contexts.Encyclopedium", "encyclopedia")
                        .WithMany("Annotations")
                        .HasForeignKey("encyclopediaId")
                        .IsRequired()
                        .HasConstraintName("Annotation_Encyclopedia_id_fk");

                    b.HasOne("Infrastructure.Contexts.Theme", "theme")
                        .WithMany("Annotations")
                        .HasForeignKey("themeId")
                        .IsRequired()
                        .HasConstraintName("Annotation_Theme_Id_fk");

                    b.Navigation("encyclopedia");

                    b.Navigation("theme");
                });

            modelBuilder.Entity("Infrastructure.Contexts.Encyclopedium", b =>
                {
                    b.HasOne("Infrastructure.Contexts.Scribe", "scribe")
                        .WithMany("Encyclopedia")
                        .HasForeignKey("scribeId")
                        .IsRequired()
                        .HasConstraintName("Encyclopedia_Scribe_id_fk");

                    b.Navigation("scribe");
                });

            modelBuilder.Entity("Infrastructure.Contexts.Encyclopedium", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("Infrastructure.Contexts.Scribe", b =>
                {
                    b.Navigation("Encyclopedia");
                });

            modelBuilder.Entity("Infrastructure.Contexts.Theme", b =>
                {
                    b.Navigation("Annotations");
                });
#pragma warning restore 612, 618
        }
    }
}
